spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: root
    password: wydemo
    url: jdbc:mysql://localhost:3306/unifiedplatform?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
#  jackson:
#    default-property-inclusion: non_null
  http:
    multipart:
      maxFileSize: 1000Mb
      maxRequestSize: 1000Mb
server:
  port: 8100
  error:
    include-exception: true
    include-message: always

uploadPath:
  /usr/java/wyxyScript/image/
